[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gocolly/colly"
  version = "1.1.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"
